### ISSUE TITLE
`run.sh`: non-network local connections, and docker:  unknown or invalid runtime name: nvidia.

### ISSUE THREAD

**Issue by mxochicale** [PUTvision/LunarSim#2]
First of all Great work! @bartoszptak  and @dpieczynski 

I am trying to have a go to your work but I get this one:
```
bash ./run.sh
non-network local connections being added to access control list
docker: Error response from daemon: unknown or invalid runtime name: nvidia.
See 'docker run --help'.
```
I successfully built docker tagged lunarsim:latest . Also installed nvidia-docker2 and nvidia-container-toolkit in my Ubuntu 20.04x64 machine which does have a GPU.
```
sudo apt-get install -y nvidia-container-toolkit
sudo apt install -y nvidia-docker2
sudo systemctl daemon-reload
sudo systemctl restart docker
```
Do you have any advice? Do I need to have a machine with GPU as a requirement? 

Thanks, Miguel
PS. Happy to create a PR to improve reproducibility :)

**Comment by bartoszptak** [comment]
Hi,
We discovered that the flag `--runtime nvidia` is the issue in the new Nvidia-docker2 API. So we removed it from `./run.sh` and `run_once.sh` scripts.
